- hosts: web
  become: yes
  vars:
    nama: "Saiful Habib, S.Pd."
    kelas: "XI TJKT 0"
  tasks:
    - name: Install nginx
      apt:
        name:
          - nginx
        state: present
        update_cache: yes

    - name: Ensure services are running
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Deploy HTML test page
      template:
        src: test.html.j2
        dest: /var/www/html/test.html
        owner: www-data
        group: www-data
        mode: "0644"
# Tugas XII TJKT 1:
# Buat variable baru: cita_cita, motto, rencana_setelah_lulus
# Buat HTML baru, profil.html
# Masukkan ke dalam proyek ansible ini!
# Up ke server menggunakan ansible!
